server:  
  port: 8080  
  
spring:  
  cloud:  
    gateway:  
      discovery:  
        locator:  
          enabled: true  
          lower-case-service-id: true  
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: trajet-service
          uri: lb://TRAJET-SERVICE
          predicates:
            - Path=/api/trajets/**
          filters:
            - StripPrefix=1

        - id: geolocalisation-service
          uri: lb://GEOLOCALISATION-SERVICE
          predicates:
            - Path=/api/locations/**
          filters:
            - StripPrefix=1

        - id: paiement-service
          uri: lb://PAIEMENT-SERVICE
          predicates:
            - Path=/api/paiements/**
          filters:
            - StripPrefix=1

        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/api/tickets/**
          filters:
            - StripPrefix=1

        - id: abonnement-service
          uri: lb://ABONNEMENT-SERVICE
          predicates:
            - Path=/api/abonnements/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
  
eureka:  
  client:  
    service-url:  
      defaultZone: http://localhost:8761/eureka/