server:  
  port: 8084  
  
spring:  
  datasource:  
    url: jdbc:postgresql://postgres-auth:5435/geolocalisation_db  
    username: ${GEO_DB_USER:wasalny_user}  
    password: ${GEO_DB_PASSWORD:wasalny_password}  
  jpa:  
    hibernate:  
      ddl-auto: update  
    show-sql: true  
    properties:  
      hibernate:  
        dialect: org.hibernate.dialect.PostgreSQLDialect  
  
eureka:  
  client:  
    service-url:  
      defaultZone: http://eureka-server:8761/eureka/