server:  
  port: 8085  
  
spring:  
  datasource:  
    url: jdbc:postgresql://postgres-auth:5436/ticket_db  
    username: ${TICKET_DB_USER:wasalny_user}  
    password: ${TICKET_DB_PASSWORD:wasalny_password}  
  jpa:  
    hibernate:  
      ddl-auto: update  
    show-sql: true  
    properties:  
      hibernate:  
        dialect: org.hibernate.dialect.PostgreSQLDialect  
  rabbitmq:  
    host: localhost  
    port: 5672  
    username: ${RABBITMQ_USER:admin}  
    password: ${RABBITMQ_PASSWORD:admin}  
  
eureka:  
  client:  
    service-url:  
      defaultZone: http://eureka-server:8761/eureka/