spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:4088/notification_db
    username: wasalny_user
    password: wasalny_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
