version: '3.8'

services:
  # PostgreSQL Databases
  postgres-auth:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: wasalny_user
      POSTGRES_PASSWORD: wasalny_password
    ports:
      - "5437:5432"
    networks:
      - wasalny-network

  postgres-user:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: wasalny_user
      POSTGRES_PASSWORD: wasalny_password
    ports:
      - "5434:5432"
    networks:
      - wasalny-network

  postgres-trajet:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: trajet_db
      POSTGRES_USER: wasalny_user
      POSTGRES_PASSWORD: wasalny_password
    ports:
      - "5432:5432"
    networks:
      - wasalny-network

  postgres-geo:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: geolocalisation_db
      POSTGRES_USER: wasalny_user
      POSTGRES_PASSWORD: wasalny_password
    ports:
      - "5435:5432"
    networks:
      - wasalny-network

  postgres-paiement:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: paiement_db
      POSTGRES_USER: wasalny_user
      POSTGRES_PASSWORD: wasalny_password
    ports:
      - "5433:5432"
    networks:
      - wasalny-network

  postgres-ticket:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ticket_db
      POSTGRES_USER: wasalny_user
      POSTGRES_PASSWORD: wasalny_password
    ports:
      - "5436:5432"
    networks:
      - wasalny-network

  postgres-abonnement:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: abonnement_db
      POSTGRES_USER: wasalny_user
      POSTGRES_PASSWORD: wasalny_password
    ports:
      - "5438:5432"
    networks:
      - wasalny-network

  postgres-notification:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: wasalny_user
      POSTGRES_PASSWORD: wasalny_password
    ports:
      - "5439:5432"
    networks:
      - wasalny-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - wasalny-network

  # Redis
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redis_password
    ports:
      - "6379:6379"
    networks:
      - wasalny-network

networks:
  wasalny-network:
    driver: bridge
