spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:4086/auth_db
    username: wasalny_user
    password: wasalny_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
