spring:  
  application:  
    name: api-gateway  
  config:  
    import: "optional:configserver:http://config-server:8888"  
  cloud:  
    config:  
      fail-fast: false  
      retry:  
        max-attempts: 20  
        initial-interval: 1000  
        max-interval: 2000  
  
server:  
  port: 8080