spring:
  application:
    name: paiement-service
  datasource:
    url: jdbc:postgresql://localhost:4082/paiement_db
    username: wasalny_user
    password: wasalny_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
